name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: [completed]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Stop the old container
      run: docker stop basic-aws-cicd
    - name: Delete the old container
      run: docker rm basic-aws-cicd
    - name: Delete the old image
      run: docker rmi nur5480/basic-aws-cicd
    - name: Pull the image from DockerHub
      run: docker pull nur5480/basic-aws-cicd
    - name: Run the new  image
      run: docker run -d --name basic-aws-cicd -p 5000:5000 nur5480/basic-aws-cicd

    

    
