name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: [completed]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Stop the old container
      run: docker stop basic-aws-cicd || true
    
    - name: Delete the old container
      run: docker rm basic-aws-cicd || true
    
    - name: Delete the old image
      run: docker rmi ${{secrets.DOCKER_USERNAME}}/basic-aws-cicd:latest || true

    - name: Pull the image from DockerHub
      run: docker pull ${{secrets.DOCKER_USERNAME}}/basic-aws-cicd:latest
    
    - name: Run the new container
      run:  docker run -d -p 5000:5000 --name basic-aws-cicd ${{secrets.DOCKER_USERNAME}}/basic-aws-cicd:latest

    

    
