name: Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo "${{secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/basic-aws-cicd:latest

    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/basic-aws-cicd:latest
